services:
  db:
    image: mariadb:11.2
    environment:
      - MARIADB_USER=redmine
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=redmine_production
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./srv/mariadb:/var/lib/mysql
      # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
    command:
      - mariadbd
      # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
      - --transaction-isolation=READ-COMMITTED
      # Configure 4byte utf8 support for full unicode support (all emojis), this requires manual conversion for existing tables. See README
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3

  redmine:
    image: redmine:5.1.4
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Madrid
      - REDMINE_DB_ENCODING=utf8mb4
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=password
      - REDMINE_DB_DATABASE=redmine_production

    ports:
      - "8080:3000"
    volumes:
      - ./srv/redmine:/home/redmine/data
